// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApnV8s2SvxKzA6tQHy4ZsCvlpsrifBj1U',
    appId: '1:1005410879055:web:194f625a5d732116eb0c3a',
    messagingSenderId: '1005410879055',
    projectId: 'dhuwitku-f5917',
    authDomain: 'dhuwitku-f5917.firebaseapp.com',
    storageBucket: 'dhuwitku-f5917.firebasestorage.app',
    measurementId: 'G-M1E0BSKCGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeld57yolwepi65qeW0HajxyfCRfmVHsY',
    appId: '1:1005410879055:android:d9ca6345c841c2abeb0c3a',
    messagingSenderId: '1005410879055',
    projectId: 'dhuwitku-f5917',
    storageBucket: 'dhuwitku-f5917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsX8MIvVqJMSsjPhTKlvqUfEtRYr7aT9I',
    appId: '1:1005410879055:ios:994ae8e477af0d21eb0c3a',
    messagingSenderId: '1005410879055',
    projectId: 'dhuwitku-f5917',
    storageBucket: 'dhuwitku-f5917.firebasestorage.app',
    androidClientId: '1005410879055-dqtr2qe2ebk0nt17e23fa3p9e3nh99hb.apps.googleusercontent.com',
    iosClientId: '1005410879055-l1dbta118jqv7d9d7b00or3srsb4705c.apps.googleusercontent.com',
    iosBundleId: 'com.mdcnugroho.dhuwitku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsX8MIvVqJMSsjPhTKlvqUfEtRYr7aT9I',
    appId: '1:1005410879055:ios:e0a46ca8e11edda3eb0c3a',
    messagingSenderId: '1005410879055',
    projectId: 'dhuwitku-f5917',
    storageBucket: 'dhuwitku-f5917.firebasestorage.app',
    androidClientId: '1005410879055-dqtr2qe2ebk0nt17e23fa3p9e3nh99hb.apps.googleusercontent.com',
    iosClientId: '1005410879055-e9tro59ilc6dc2l6jk0u793h144um8sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhuwitku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApnV8s2SvxKzA6tQHy4ZsCvlpsrifBj1U',
    appId: '1:1005410879055:web:c45d644d4c4f905aeb0c3a',
    messagingSenderId: '1005410879055',
    projectId: 'dhuwitku-f5917',
    authDomain: 'dhuwitku-f5917.firebaseapp.com',
    storageBucket: 'dhuwitku-f5917.firebasestorage.app',
    measurementId: 'G-1E369WXR47',
  );
}
